name: Build Repository

on:
  push:
    branches: [ main ]
    paths:
      - 'plugin.video.maltracker/**'
      - 'repository.maltracker/**'
      - 'create_repo.py'

permissions:
  contents: write


jobs:
  build-repository:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Build repository
      run: |
        # Build addon first
        cd plugin.video.maltracker
        zip -r ../plugin.video.maltracker.zip . -x "*.pyc" "__pycache__/*"
        cd ..
        
        # Create addons.xml manually
        echo '<?xml version="1.0" encoding="UTF-8"?>' > addons.xml
        echo '<addons>' >> addons.xml
        sed '1d' plugin.video.maltracker/addon.xml >> addons.xml
        sed '1d' repository.maltracker/addon.xml >> addons.xml
        echo '</addons>' >> addons.xml
        
        # Create MD5
        md5sum addons.xml | cut -d' ' -f1 > addons.xml.md5
        
        # Create repository ZIP
        cd repository.maltracker
        zip -r ../repository.maltracker.zip .
        cd ..
        
        echo "✓ Repository built successfully"
        echo "Generated files:"
        ls -la *.xml *.zip 2>/dev/null || echo "No files generated"
        
    - name: Verify files
      run: |
        if [ ! -f "addons.xml" ]; then echo "❌ addons.xml missing"; exit 1; fi
        if [ ! -f "repository.maltracker.zip" ]; then echo "❌ repository.maltracker.zip missing"; exit 1; fi
        echo "✅ All required files present"
      
    - name: Create repository release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          addons.xml
          addons.xml.md5
          plugin.video.maltracker.zip
          repository.maltracker.zip
        tag_name: repo-v1.0.${{ github.run_number }}
        name: Repository v1.0.${{ github.run_number }}
        body: |
          ## 📦 MAL Tracker Repository
          
          **Archivos incluidos:**
          - `repository.maltracker.zip` - Instalar repositorio
          - `plugin.video.maltracker.zip` - Addon directo
          - `addons.xml` - Lista de addons
          - `addons.xml.md5` - Checksum
          
          **🌐 URL del repositorio:**
          ```
          https://deus-dei.github.io/MAL-Tracker-For-Kodi/repository.maltracker.zip
          ```
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}