name: Build Repository

on:
  push:
    branches: [ main ]
    paths:
      - 'plugin.video.maltracker/**'
      - 'repository.maltracker/**'
      - 'create_repo.py'


jobs:
  build-repository:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Build repository
      run: |
        python create_repo.py
        echo "✓ Repository built successfully"
        echo "Generated files:"
        ls -la *.xml *.zip 2>/dev/null || echo "No files generated"
        
    - name: Verify files
      run: |
        if [ ! -f "addons.xml" ]; then echo "❌ addons.xml missing"; exit 1; fi
        if [ ! -f "repository.maltracker.zip" ]; then echo "❌ repository.maltracker.zip missing"; exit 1; fi
        echo "✅ All required files present"
      
    - name: Upload repository artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kodi-repository
        path: |
          addons.xml
          addons.xml.md5
          *.zip
        retention-days: 30