name: Build Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Build all files
      run: |
        # Build addon
        cd plugin.video.maltracker
        zip -r ../plugin.video.maltracker.zip . -x "*.pyc" "__pycache__/*"
        cd ..
        
        # Create addons.xml completo
        echo '<?xml version="1.0" encoding="UTF-8"?>' > addons.xml
        echo '<addons>' >> addons.xml
        sed '1d' plugin.video.maltracker/addon.xml >> addons.xml
        sed '1d' repository/repository.maltracker/addon.xml >> addons.xml
        echo '</addons>' >> addons.xml
        
        # Create MD5
        md5sum addons.xml | cut -d' ' -f1 > addons.xml.md5
        
        # Create repository ZIP
        cd repository/repository.maltracker
        zip -r ../../repository.maltracker.zip .
        cd ../..
        
        # Copy files for Pages
        cp repository/pages/index.html .
        cp README.md .
        
        echo "✓ All files built for Pages"
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
        force_orphan: true
        enable_jekyll: false
        commit_message: 'Deploy pages ${{ github.sha }}'