name: Build Addon

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build addon
      run: |
        cd plugin.video.maltracker
        zip -r ../plugin.video.maltracker.zip . -x "*.pyc" "__pycache__/*" "*.log" "*.tmp"
        cd ..
        echo "✓ Addon built successfully"
        
    - name: Upload addon artifact
      uses: actions/upload-artifact@v4
      with:
        name: plugin.video.maltracker
        path: plugin.video.maltracker.zip
        retention-days: 30
        
    - name: Create auto release
      uses: softprops/action-gh-release@v1
      with:
        files: plugin.video.maltracker.zip
        generate_release_notes: true
        tag_name: v1.0.${{ github.run_number }}
        name: MAL Tracker v1.0.${{ github.run_number }}
        body: |
          ## MAL Tracker Auto Release
          
          🎬 **Características:**
          - Integración MAL/AniList
          - Scrapers avanzados
          - Auto-reproducción
          - 16 sitios streaming
          
          📦 **Instalación:**
          Descargar `plugin.video.maltracker.zip`
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}