name: Build MAL Tracker Addon

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create addon zip
      run: |
        cd plugin.video.maltracker
        zip -r ../plugin.video.maltracker.zip . -x "*.pyc" "__pycache__/*" "*.log" "*.tmp"
        cd ..
        
    - name: Upload addon artifact
      uses: actions/upload-artifact@v4
      with:
        name: plugin.video.maltracker
        path: plugin.video.maltracker.zip
        retention-days: 30
        
    - name: Auto-create release (on version change)
      if: startsWith(github.ref, 'refs/tags/') || contains(github.event.head_commit.message, '[release]')
      uses: softprops/action-gh-release@v1
      with:
        files: plugin.video.maltracker.zip
        generate_release_notes: true
        tag_name: auto-${{ github.run_number }}
        name: Auto Release ${{ github.run_number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}