name: Build Repository

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-repo:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Create repository files
      run: |
        python create_repo.py
        
    - name: Upload repository artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kodi-repository
        path: |
          addons.xml
          addons.xml.md5
          *.zip
        retention-days: 30
        compression-level: 6
        
    # GitHub Pages deployment moved to separate workflow