name: Build and Release Addon
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Empaquetar addon
        run: |
          zip -r plugin.video.maltracker.zip . -x '*.git*' '.github/*'
      - name: Obtener hash corto del commit
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Crear release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: auto-${{ steps.vars.outputs.sha_short }}
          name: Release ${{ steps.vars.outputs.sha_short }}
          files: plugin.video.maltracker.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
